name: libphonenumber_plugin
description: Flutter package for Google libphonenumber, for Android and Web. Uses Flutter Federated Package for interoperability.
version: 0.2.1
homepage: https://github.com/natintosh/plugin_libphonenumber.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  libphonenumber_platform_interface: ^0.3.0

  libphonenumber_web: ^0.2.0

  libphonenumber: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/libphonenumber_plugin/js/libphonenumber.js
    - packages/libphonenumber_plugin/js/stringbuffer.js
    - assets/js/libphonenumber.js
    - assets/js/stringbuffer.js

  plugin:
    platforms:
      android:
        package: com.example.libphonenumber_plugin
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: FLTLibphonenumberPlugin
      web:
        default_package: libphonenumber_web
