name: libphonenumber_plugin
description: Flutter package for Google libphonenumber.
version: 0.1.0
homepage: https://github.com/natintosh/plugin_libphonenumber.git

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  
  # libphonenumber_platform_interface: ^0.2.0
  libphonenumber_platform_interface:
    path: ../libphonenumber_platform_interface

  # libphonenumber_web: ^0.1.1
  libphonenumber_web:
    path: ../libphonenumber_web

  libphonenumber: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/libphonenumber_plugin/js/libphonenumber.js
    - packages/libphonenumber_plugin/js/stringbuffer.js
    - assets/js/libphonenumber.js
    - assets/js/stringbuffer.js

  plugin:
    platforms:
      android:
        package: com.example.libphonenumber_plugin
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: FLTLibphonenumberPlugin
      web:
        default_package: libphonenumber_web
