name: libphonenumber_web
description: The web implementation of libphonenumber
version: 0.2.0+1
homepage: https://github.com/natintosh/plugin_libphonenumber.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.5
#  libphonenumber_platform_interface: ^0.3.1

  libphonenumber_platform_interface:
    path: ../libphonenumber_platform_interface

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: LibPhoneNumberPlugin
        fileName: libphonenumber_web.dart
