name: libphonenumber_platform_interface
description: Libphonenumber Platform Interface with MethodChannels and Utils classes.
version: 0.1.0
homepage: https://github.com/natintosh/plugin_libphonenumber

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
